name: music_ui
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  percent_indicator: ^4.2.3

flutter:
  uses-material-design: true
  assets:
    - Assets/image1.png
    - Assets/image2.png
    - Assets/image8.png
    - Assets/image9.png
    - Assets/image3.png
    - Assets/image4.png
    - Assets/image5.png
    - Assets/image6.png
    - Assets/image7.png
    - Assets/image10.png
    - Assets/image17.png
    - Assets/image12.png
    - Assets/image13.png
    - Assets/image14.png
    - Assets/image15.png
    - Assets/image16.png




    